/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	v12 "github.com/ing-bank/quota-scaler/pkg/scalerclient/apis/quotaautoscaler/v1"
	"github.com/ing-bank/quota-scaler/pkg/scalerclient/client/clientset/versioned"
	"github.com/ing-bank/quota-scaler/pkg/scalerclient/client/informers/externalversions/internalinterfaces"
	v1 "github.com/ing-bank/quota-scaler/pkg/scalerclient/client/listers/quotaautoscaler/v1"
	time "time"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// QuotaAutoscalerInformer provides access to a shared informer and lister for
// QuotaAutoscalers.
type QuotaAutoscalerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.QuotaAutoscalerLister
}

type quotaAutoscalerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewQuotaAutoscalerInformer constructs a new informer for QuotaAutoscaler type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewQuotaAutoscalerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredQuotaAutoscalerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredQuotaAutoscalerInformer constructs a new informer for QuotaAutoscaler type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredQuotaAutoscalerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IchpV1().QuotaAutoscalers(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IchpV1().QuotaAutoscalers(namespace).Watch(context.TODO(), options)
			},
		},
		&v12.QuotaAutoscaler{},
		resyncPeriod,
		indexers,
	)
}

func (f *quotaAutoscalerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredQuotaAutoscalerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *quotaAutoscalerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&v12.QuotaAutoscaler{}, f.defaultInformer)
}

func (f *quotaAutoscalerInformer) Lister() v1.QuotaAutoscalerLister {
	return v1.NewQuotaAutoscalerLister(f.Informer().GetIndexer())
}
