{{- $container := .Values.containers.scaler -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quotascaler-clusterrole
rules:
  - apiGroups: ["ichp.ing.net"]
    resources: ["quotaautoscalers"]
    verbs: ["watch", "list"]
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["watch", "list", "get", "patch"]
  - apiGroups: [""]
    resources: ["replicationcontrollers"]
    verbs: ["watch", "list", "get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["watch", "list", "get", "create"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "statefulsets", "daemonsets"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quotascaler-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: quotascaler-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ $container.name }}-sa
    namespace: {{ $container.namespace }}
